name: Cleanup Old GHCR Develop Images

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  delete-old-image-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Necessary to delete package versions
      contents: read # Only if your workflow needs to read repository content

    steps:
      - name: Delete old versions of develop image
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'rowerg-diary'
          package-type: 'container'
          owner: ${{ github.repository_owner }} 
          min-versions-to-keep: 1 # Keep the 5 most recently pushed versions. Adjust as needed.
          token: ${{ secrets.GHCR_TOKEN }} 
          delete-only-untagged-versions: "true"