name:  Deploy Develop Branch to GHCR

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI
  push:
    branches:
      - develop # Trigger on pushes to the develop branch

concurrency: # Ensures only one deployment job runs at a time for a given ref
  group: deploy-${{ github.ref }}
  cancel-in-progress: true # Cancels any in-progress runs for the same group when a new one starts

jobs:
  build_and_push_develop:
    runs-on: ubuntu-latest

    permissions: # Recommended: Explicitly grant permissions needed by this workflow
      contents: read   # To checkout the repository code
      packages: write  # To push images to GitHub Container Registry (GHCR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Automatically gets the GitHub username or organization name
          password: ${{ secrets.GHCR_TOKEN }}     # Uses the PAT stored as a GitHub Secret


      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64   # Defines the target platform for the image
          push: true               # Tells the action to push the image to the registry
          tags: ghcr.io/pinionless/rowergdiary:develop # Tag with :develop

      - name: Logout from GitHub Container Registry
        if: always()
        run: docker logout ghcr.io # Ensures logout even if previous steps fail